In [71]:
import numpy as np
import time

In [72]:
a = np.zeros(4);
b = np.zeros((4,));
print(f"np.zeros(4) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
print(f"np.zeros(4) : b = {b}, b shape = {b.shape}, b data type = {b.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4) : b = [0. 0. 0. 0.], b shape = (4,), b data type = float64


In [73]:
a = np.array([1, 2, 4, 7, 9])
b = np.array([1, 2.3, 4, 7, 9])

print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
print(f"b = {b}, b shape = {b.shape}, b data type = {b.dtype}")



a = [1 2 4 7 9], a shape = (5,), a data type = int64
b = [1.  2.3 4.  7.  9. ], b shape = (5,), b data type = float64


# INDEXING

In [74]:
a = np.arange(10)
print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
print(f"a.shape = {a.shape[0]}")
print(f"a[-1] = {a[-3:]}")

a = [0 1 2 3 4 5 6 7 8 9], a shape = (10,), a data type = int64
a.shape = 10
a[-1] = [7 8 9]


# SLICING

In [75]:
a = np.arange(10)
print(f"a : {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1]
print(f"c : {c}")
d = a[2:7:2]
print(f"d : {d}")

c = a[3:] # print all element starting from 3rd indext to last
print(f"a[3:] : {c}")

a : [0 1 2 3 4 5 6 7 8 9]
c : [2 3 4 5 6]
d : [2 4 6]
a[3:] : [3 4 5 6 7 8 9]


# Single Vector Operations

In [76]:
a = np.array([1, 2, 4, 7])

b = -a
print(f"b: {b}")

b = np.sum(a)
print(f"np.sum(a) = {b}")

c = np.mean(a)
print(f"mean of a : {c}")

d = a**2
print(f"a**2 = {d}")



b: [-1 -2 -4 -7]
np.sum(a) = 14
mean of a : 3.5
a**2 = [ 1  4 16 49]


# Vector vector element-wise opearation

In [77]:
a = np.array([1, 2, 3, 7])
b = np.array([3, 5, 8, 9])

print(f"binary ops a + b = {a+b}")

try:
    c = np.array([1, 2])
    d = a + c
except Exception as e:
    print("the error message :")
    print(e)


binary ops a + b = [ 4  7 11 16]
the error message :
operands could not be broadcast together with shapes (4,) (2,) 


# Scalar Vector Operations

In [78]:
a = np.array([2, 3, 5, 7])
b = 5*a;
print(f"b: {b}")

b: [10 15 25 35]


## Vector Vector Dot Product

In [79]:
def my_dot(a, b):
    x = 0
    for i in range (a.shape[0]):
        x = x + a[i]*b[i]
    return x

In [80]:
a = np.array([1,2, 3, 5]);
b = np.array([-1, 2, 4, 10]);

print(f"my_dot(a, b): {my_dot(a, b)}")


my_dot(a, b): 65


In [81]:
a = np.array([1,2, 3, 5]);
b = np.array([-1, 2, 4, 10]);
c = np.dot(a, b)
print(f"dot product of a and b is : {c}")

d = np.dot(b, a)
print(f"dot product of b and a is : {d}")


dot product of a and b is : 65
dot product of b and a is : 65


# Comparing Speed : Vector vs For Loop

In [82]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(f"np.dot(a, b) = {c: .4f}")
print(f"vectorization version dot prod duration: {1000*(toc-tic): .4f} ms")


tic = time.time();
c = my_dot(a, b)
toc = time.time();
print(f"my_dot(a, b) = {c: .4f}")
print(f"For loop version dot prod duration: {1000*(toc-tic): .4f} ms")
del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
vectorization version dot prod duration:  11.2290 ms
my_dot(a, b) =  2501072.5817
For loop version dot prod duration:  868.6678 ms


# Matrices



In [83]:
a = np.zeros((2, 5))
print(f"a = {a}")

a = np.random.random_sample((2, 2))
print(f"a shape = {a.shape}, a = {a}")


a = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
a shape = (2, 2), a = [[0.44236513 0.04997798]
 [0.77390955 0.93782363]]


In [84]:
a = np.array([[5, 3, 2], [3, 9, 8]])
print(f"a = {a}")

a = [[5 3 2]
 [3 9 8]]


# Operation on Matrices

In [85]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.


# Slicing

In [86]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
